name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

jobs:
  build-cross-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install mamba
      run: |
        conda install -c conda-forge mamba
    - name: Install dependencies
      run: |
        mamba env update --file environment-test.yml --name base
    - name: Install current project in dev mode
      run: |
        pip install -e .
    - name: Install pytest
      run: |
        mamba install -c conda-forge pytest
    - name: Test with pytest
      run: |
        pytest
    - name: Test Convert
      run: |
        python tests/test_convert.py
    - name: Test JVM
      run: |
        python tests/test_jvm.py
    - name: Test Pandas
      run: |
        python tests/test_pandas.py
